<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
           'employee-list',
           'employee-create',
           'employee-update',
           'customers-list',
           'customers-create',
           'customers-update',
           'site-setting-list',
           'site-setting-create',
           'site-setting-update',
           'taxes-list',
           'taxes-create',
           'taxes-update',
           'units-list',
           'units-create',
           'units-update',
           'payment-methods-list',
           'payment-methods-create',
           'payment-methods-update',
           'pumps-list',
           'pumps-create',
           'pumps-update',
           'product-list',
           'product-create',
           'product-update',
           'leads-list',
           'leads-create',
           'leads-update',
           'sales-inquirie-list',
           'sales-inquirie-create',
           'sales-inquirie-update',
           'sales-estimates-list',
           'sales-estimates-create',
           'sales-estimates-update',
           'sales-proposals-list',
           'sales-proposals-create',
           'sales-proposals-update',
           'sales-bookings-list',
           'sales-bookings-create',
           'sales-bookings-update',
           'sales-invoice-list',
           'sales-invoice-create',
           'sales-invoice-update',
           'sales-payments-list',
           'sales-payments-create',
           'sales-payments-update',
           'sales-account-list',
           'sales-account-create',
           'sales-account-update',
           'sales-account-statement-list',
           'sales-account-statement-create',
           'sales-account-statement-update',
           'sales-rservations-list',
           'sales-rservations-create',
           'sales-rservations-update',
           'dispatch-order-list',
           'dispatch-order-create',
           'dispatch-order-update',
           'dispatch-driver-list',
           'dispatch-driver-create',
           'dispatch-driver-update',
           'dispatch-vechicle-list',
           'dispatch-vechicle-create',
           'dispatch-vechicle-update',
           'booking-statement-list',
           'booking-statement-create',
           'booking-statement-update',
           'purchase-commodity-group-list',
           'purchase-commodity-group-create',
           'purchase-commodity-group-update',
           'purchase-item-list',
           'purchase-item-create',
           'purchase-item-update',
           'purchase-vendor-list',
           'purchase-vendor-create',
           'purchase-vendor-update',
           'purchase-request-list',
           'purchase-request-create',
           'purchase-request-update',
           'purchase-estimates-list',
           'purchase-estimates-create',
           'purchase-estimates-update',
           'purchase-orders-list',
           'purchase-orders-create',
           'purchase-orders-update',
           'parts-list',
           'parts-create',
           'parts-update',
           'supplier-list',
           'supplier-create',
           'supplier-update',
           'manufacturer-list',
           'manufacturer-create',
           'manufacturer-update',
           'make/model/year-list',
           'make/model/year-create',
           'make/model/year-update',
           'parts-stock-list',
           'parts-stock-create',
           'parts-stock-update',
           'purchase-parts-list',
           'purchase-parts-create',
           'purchase-parts-update',
           'repair-list',
           'repair-create',
           'repair-update',
           'print-labels-list',
           'print-labels-create',
           'print-labels-update',
           'roles-list',
           'roles-create',
           'roles-update',
           'attendance-list',
           'attendance-create',
           'attendance-update',
           'leave-tracker-list',
           'leave-tracker-create',
           'leave-tracker-update',
           'maintenance-category-list'
        ];
   
        foreach ($permissions as $permission) {
             Permission::create(['name' => $permission]);
        }
    }
}
